"""Add user roles and additional fields

Revision ID: add_user_roles
Revises:
Create Date: 2024-01-01 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_user_roles'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # First, add new columns to users table
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('role', sa.Enum('USER', 'ADMIN', 'SUPER_ADMIN', name='userrole'), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))

    # Create unique index for email
    op.create_index('ix_users_email', 'users', ['email'], unique=True)

    # Set default values for existing users
    op.execute("UPDATE users SET role = 'USER', is_active = true, created_at = datetime('now') WHERE role IS NULL")
    op.execute("UPDATE users SET is_active = true WHERE is_active IS NULL")
    op.execute("UPDATE users SET created_at = datetime('now') WHERE created_at IS NULL")

    # Make the email column non-nullable after setting defaults (optional, keep nullable for flexibility)
    # op.alter_column('users', 'email', nullable=False)

    # Make role non-nullable after setting defaults
    op.alter_column('users', 'role', nullable=False)

    # Make is_active non-nullable after setting defaults
    op.alter_column('users', 'is_active', nullable=False)

    # Make created_at non-nullable after setting defaults
    op.alter_column('users', 'created_at', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove columns
    op.drop_index('ix_users_email', table_name='users')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    op.drop_column('users', 'email')

    # ### end Alembic commands ###